const PARTICLE_CONCENTRATION_PM1_0_NORMAL = 'concentration_pm1.0_normal';
const PARTICLE_CONCENTRATION_PM2_5_NORMAL = 'concentration_pm2.5_normal';
const PARTICLE_CONCENTRATION_PM10_NORMAL = 'concentration_pm10_normal';

const PARTICLE_CONCENTRATION_PM1_0_ATMOS = 'concentration_pm1.0_atmos';
const PARTICLE_CONCENTRATION_PM2_5_ATMOS = 'concentration_pm2.5_atmos';
const PARTICLE_CONCENTRATION_PM10_ATMOS = 'concentration_pm10_atmos';

const PARTICLE_COUNT_PM0_3 = 'count_pm_0.3';
const PARTICLE_COUNT_PM0_5 = 'count_pm_0.5';
const PARTICLE_COUNT_PM1_0 = 'count_pm_1.0';
const PARTICLE_COUNT_PM2_5 = 'count_pm_2.5';
const PARTICLE_COUNT_PM5 = 'count_pm_5';
const PARTICLE_COUNT_PM10 = 'count_pm_10';

const TEMPERATURE = 'temperature';
const HUMIDITY = 'humidity';

const FORMALDEHYDE = 'formaldehyde';
const VERSION = 'version';
const ERROR = 'error';
const RETAINED = 'retained';

const NORMAL_PMSXXXX = [
    PARTICLE_CONCENTRATION_PM1_0_NORMAL,
    PARTICLE_CONCENTRATION_PM1_0_NORMAL,
    PARTICLE_CONCENTRATION_PM2_5_NORMAL,
    PARTICLE_CONCENTRATION_PM2_5_NORMAL,
    PARTICLE_CONCENTRATION_PM10_NORMAL,
    PARTICLE_CONCENTRATION_PM10_NORMAL,
    PARTICLE_CONCENTRATION_PM1_0_ATMOS,
    PARTICLE_CONCENTRATION_PM1_0_ATMOS,
    PARTICLE_CONCENTRATION_PM2_5_ATMOS,
    PARTICLE_CONCENTRATION_PM2_5_ATMOS,
    PARTICLE_CONCENTRATION_PM10_ATMOS,
    PARTICLE_CONCENTRATION_PM10_ATMOS,
    PARTICLE_COUNT_PM0_3,
    PARTICLE_COUNT_PM0_3,
    PARTICLE_COUNT_PM0_5,
    PARTICLE_COUNT_PM0_5,
    PARTICLE_COUNT_PM1_0,
    PARTICLE_COUNT_PM1_0,
    PARTICLE_COUNT_PM2_5,
    PARTICLE_COUNT_PM2_5,
    PARTICLE_COUNT_PM5,
    PARTICLE_COUNT_PM5,
    PARTICLE_COUNT_PM10,
    PARTICLE_COUNT_PM10,
    VERSION,
    ERROR
];

module.exports = {
    PMS1003: NORMAL_PMSXXXX,
    PMSA003: NORMAL_PMSXXXX,
    PMS6003: NORMAL_PMSXXXX,
    PMS5003: NORMAL_PMSXXXX,
    PMS5003I: NORMAL_PMSXXXX,
    PMS5003P: NORMAL_PMSXXXX,
    PMS3003: [
        PARTICLE_CONCENTRATION_PM1_0_NORMAL,
        PARTICLE_CONCENTRATION_PM1_0_NORMAL,
        PARTICLE_CONCENTRATION_PM2_5_NORMAL,
        PARTICLE_CONCENTRATION_PM2_5_NORMAL,
        PARTICLE_CONCENTRATION_PM10_NORMAL,
        PARTICLE_CONCENTRATION_PM10_NORMAL,
        PARTICLE_CONCENTRATION_PM1_0_ATMOS,
        PARTICLE_CONCENTRATION_PM1_0_ATMOS,
        PARTICLE_CONCENTRATION_PM2_5_ATMOS,
        PARTICLE_CONCENTRATION_PM2_5_ATMOS,
        PARTICLE_CONCENTRATION_PM10_ATMOS,
        PARTICLE_CONCENTRATION_PM10_ATMOS,
        RETAINED,
        RETAINED,
        RETAINED,
        RETAINED,
        RETAINED,
        RETAINED
    ],
    PMS5003T: [
        PARTICLE_CONCENTRATION_PM1_0_NORMAL,
        PARTICLE_CONCENTRATION_PM1_0_NORMAL,
        PARTICLE_CONCENTRATION_PM2_5_NORMAL,
        PARTICLE_CONCENTRATION_PM2_5_NORMAL,
        PARTICLE_CONCENTRATION_PM10_NORMAL,
        PARTICLE_CONCENTRATION_PM10_NORMAL,
        PARTICLE_CONCENTRATION_PM1_0_ATMOS,
        PARTICLE_CONCENTRATION_PM1_0_ATMOS,
        PARTICLE_CONCENTRATION_PM2_5_ATMOS,
        PARTICLE_CONCENTRATION_PM2_5_ATMOS,
        PARTICLE_CONCENTRATION_PM10_ATMOS,
        PARTICLE_CONCENTRATION_PM10_ATMOS,
        PARTICLE_COUNT_PM0_3,
        PARTICLE_COUNT_PM0_3,
        PARTICLE_COUNT_PM0_5,
        PARTICLE_COUNT_PM0_5,
        PARTICLE_COUNT_PM1_0,
        PARTICLE_COUNT_PM1_0,
        PARTICLE_COUNT_PM2_5,
        PARTICLE_COUNT_PM2_5,
        TEMPERATURE,
        TEMPERATURE,
        HUMIDITY,
        HUMIDITY,
        VERSION,
        ERROR
    ],
    PMS5003ST: [
        PARTICLE_CONCENTRATION_PM1_0_NORMAL,
        PARTICLE_CONCENTRATION_PM1_0_NORMAL,
        PARTICLE_CONCENTRATION_PM2_5_NORMAL,
        PARTICLE_CONCENTRATION_PM2_5_NORMAL,
        PARTICLE_CONCENTRATION_PM10_NORMAL,
        PARTICLE_CONCENTRATION_PM10_NORMAL,
        PARTICLE_CONCENTRATION_PM1_0_ATMOS,
        PARTICLE_CONCENTRATION_PM1_0_ATMOS,
        PARTICLE_CONCENTRATION_PM2_5_ATMOS,
        PARTICLE_CONCENTRATION_PM2_5_ATMOS,
        PARTICLE_CONCENTRATION_PM10_ATMOS,
        PARTICLE_CONCENTRATION_PM10_ATMOS,
        PARTICLE_COUNT_PM0_3,
        PARTICLE_COUNT_PM0_3,
        PARTICLE_COUNT_PM0_5,
        PARTICLE_COUNT_PM0_5,
        PARTICLE_COUNT_PM1_0,
        PARTICLE_COUNT_PM1_0,
        PARTICLE_COUNT_PM2_5,
        PARTICLE_COUNT_PM2_5,
        PARTICLE_COUNT_PM5,
        PARTICLE_COUNT_PM5,
        PARTICLE_COUNT_PM10,
        PARTICLE_COUNT_PM10,
        FORMALDEHYDE,
        FORMALDEHYDE,
        TEMPERATURE,
        HUMIDITY,
        RETAINED,
        RETAINED,
        VERSION,
        ERROR
    ],
    PMS5003S: [
        PARTICLE_CONCENTRATION_PM1_0_NORMAL,
        PARTICLE_CONCENTRATION_PM1_0_NORMAL,
        PARTICLE_CONCENTRATION_PM2_5_NORMAL,
        PARTICLE_CONCENTRATION_PM2_5_NORMAL,
        PARTICLE_CONCENTRATION_PM10_NORMAL,
        PARTICLE_CONCENTRATION_PM10_NORMAL,
        PARTICLE_CONCENTRATION_PM1_0_ATMOS,
        PARTICLE_CONCENTRATION_PM1_0_ATMOS,
        PARTICLE_CONCENTRATION_PM2_5_ATMOS,
        PARTICLE_CONCENTRATION_PM2_5_ATMOS,
        PARTICLE_CONCENTRATION_PM10_ATMOS,
        PARTICLE_CONCENTRATION_PM10_ATMOS,
        PARTICLE_COUNT_PM0_3,
        PARTICLE_COUNT_PM0_3,
        PARTICLE_COUNT_PM0_5,
        PARTICLE_COUNT_PM0_5,
        PARTICLE_COUNT_PM1_0,
        PARTICLE_COUNT_PM1_0,
        PARTICLE_COUNT_PM2_5,
        PARTICLE_COUNT_PM2_5,
        PARTICLE_COUNT_PM5,
        PARTICLE_COUNT_PM5,
        PARTICLE_COUNT_PM10,
        PARTICLE_COUNT_PM10,
        FORMALDEHYDE,
        FORMALDEHYDE
    ],
    PMS7003: NORMAL_PMSXXXX,
    PMS7003M: NORMAL_PMSXXXX,
    PMS7003P: NORMAL_PMSXXXX
};
